apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-rd
  namespace: dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rd-ns-view
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rd-ns-view
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rd-ns-view
subjects:
- kind: ServiceAccount
  name: dev-rd
  namespace: dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dev
  name: rd
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  resourceNames: ["app-cfd6fddc5-794q8"]
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  namespace: dev
  name: rd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rd
subjects:
- kind: ServiceAccount
  name: dev-rd
  namespace: dev
