apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: dev
  name: rd
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["namespaces"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  resourceNames: ["app"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods/exec"]
  verbs: ["create"]
---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: dev-rd
#   namespace: dev
# ---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-rd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rd
subjects:
- kind: ServiceAccount
  name: dev-rd
  namespace: dev