version: '3'
services:
  log:
    image: vmware/harbor-log:v1.5.0-rc1
    volumes:
      - /var/log/harbor/:/var/log/docker/:z
      - /data/common/config/log/:/etc/logrotate.d/:z
    ports:
      - 127.0.0.1:1514:10514
    networks:
      - harbor
  registry:
    image: vmware/registry-photon:v2.6.2-v1.5.0-rc1
    volumes:
      - /data/registry:/storage:z
      - /data/common/config/registry/:/etc/registry/:z
    deploy:
      restart_policy:
        delay: 40s
    networks:
      - harbor
    environment:
      - GODEBUG=netdns=cgo
    command:
      ["serve", "/etc/registry/config.yml"]
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "registry"
  mysql:
    image: vmware/harbor-db:v1.5.0-rc1
    volumes:
      - /data/database:/var/lib/mysql:z
    deploy:
      restart_policy:
        delay: 40s
    networks:
      - harbor
    env_file:
      - /data/common/config/db/env
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "mysql"
  adminserver:
    image: vmware/harbor-adminserver:v1.5.0-rc1
    env_file:
      - /data/common/config/adminserver/env
    volumes:
      - /data/config/:/etc/adminserver/config/:z
      - /data/secretkey:/etc/adminserver/key:z
      - /data/:/data/:z
    deploy:
      restart_policy:
        delay: 60s
    networks:
      - harbor
    depends_on:
      - log
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "adminserver"
  ui:
    image: vmware/harbor-ui:v1.5.0-rc1
    env_file:
      - /data/common/config/ui/env
    volumes:
      - /data/common/config/ui/app.conf:/etc/ui/app.conf:z
      - /data/common/config/ui/private_key.pem:/etc/ui/private_key.pem:z
      - /data/common/config/ui/certificates/:/etc/ui/certificates/:z
      - /data/secretkey:/etc/ui/key:z
      - /data/ca_download/:/etc/ui/ca/:z
      - /data/psc/:/etc/ui/token/:z
    deploy:
      restart_policy:
        delay: 80s
    networks:
      - harbor
    depends_on:
      - log
      - adminserver
      - registry
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "ui"
  jobservice:
    image: vmware/harbor-jobservice:v1.5.0-rc1
    env_file:
      - /data/common/config/jobservice/env
    volumes:
      - /data/job_logs:/var/log/jobs:z
      - /data/common/config/jobservice/config.yml:/etc/jobservice/config.yml:z
    deploy:
      restart_policy:
        delay: 100s
    networks:
      - harbor
    depends_on:
      - redis
      - ui
      - adminserver
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "jobservice"
  redis:
    image: vmware/redis-photon:v1.5.0-rc1
    volumes:
      - /data/redis:/data
    networks:
      - harbor
  proxy:
    image: vmware/nginx-photon:v1.5.0-rc1
    volumes:
      - /data/common/config/nginx:/etc/nginx:z
    deploy:
      restart_policy:
        delay: 120s
    networks:
      - harbor
    ports:
      - 80:80
      - 443:443
      - 4443:4443
    depends_on:
      - mysql
      - registry
      - ui
      - log
    logging:
      driver: "syslog"
      options:  
        syslog-address: "tcp://127.0.0.1:1514"
        tag: "proxy"
networks:
  harbor:
    external: false

